name: SkyWriter
main: com.pilotpax.skywriter.SkyWriter
version: 0.3

commands:
   skywrite:
      description: Writes letters in the sky
      usage: /<command> string 

permissions:
   skywriter.use:
      description: Allows you to use the skywrite command
      default: true
